AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  dog-ceo-api-golang
  
  The golang api for https://dog.ceo

Globals:
  Function:
    Timeout: 5

Resources:
  listAllBreeds:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: bin/
      Handler: listAllBreeds
      Runtime: go1.x
      Role: arn:aws:iam::633322954385:role/dog-ceo-api-golang-dev-sam
      Events:
        CatchAll:
          Type: Api
          Properties:
            Path: /breeds/list/all
            Method: GET
      Environment:
        Variables:
          IMAGE_BUCKET_NAME: "IMAGE_BUCKET_NAME env var is empty"
          FILE_BUCKET_NAME: "FILE_BUCKET_NAME env var is empty"
          BUCKET_REGION: "BUCKET_REGION env var is empty"
          CDN_DOMAIN_PREFIX: ""
  listBreeds:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: bin/
      Handler: listBreeds
      Runtime: go1.x
      Role: arn:aws:iam::633322954385:role/dog-ceo-api-golang-dev-sam
      Events:
        CatchAll:
          Type: Api
          Properties:
            Path: /breeds/list
            Method: GET
      Environment:
        Variables:
          IMAGE_BUCKET_NAME: "IMAGE_BUCKET_NAME env var is empty"
          FILE_BUCKET_NAME: "FILE_BUCKET_NAME env var is empty"
          BUCKET_REGION: "BUCKET_REGION env var is empty"
          CDN_DOMAIN_PREFIX: ""
  listSubBreeds:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: bin/
      Handler: listSubBreeds
      Runtime: go1.x
      Role: arn:aws:iam::633322954385:role/dog-ceo-api-golang-dev-sam
      Events:
        CatchAll:
          Type: Api
          Properties:
            Path: /breed/{breed1}/list
            Method: GET
      Environment:
        Variables:
          IMAGE_BUCKET_NAME: "IMAGE_BUCKET_NAME env var is empty"
          FILE_BUCKET_NAME: "FILE_BUCKET_NAME env var is empty"
          BUCKET_REGION: "BUCKET_REGION env var is empty"
          CDN_DOMAIN_PREFIX: ""
  listMasterBreedImages:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: bin/
      Handler: listMasterBreedImages
      Runtime: go1.x
      Role: arn:aws:iam::633322954385:role/dog-ceo-api-golang-dev-sam
      Events:
        CatchAll:
          Type: Api
          Properties:
            Path: /breed/{breed1}/images
            Method: GET
      Environment:
        Variables:
          IMAGE_BUCKET_NAME: "IMAGE_BUCKET_NAME env var is empty"
          FILE_BUCKET_NAME: "FILE_BUCKET_NAME env var is empty"
          BUCKET_REGION: "BUCKET_REGION env var is empty"
          CDN_DOMAIN_PREFIX: ""
  listSubBreedImages:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: bin/
      Handler: listSubBreedImages
      Runtime: go1.x
      Role: arn:aws:iam::633322954385:role/dog-ceo-api-golang-dev-sam
      Events:
        CatchAll:
          Type: Api
          Properties:
            Path: /breed/{breed1}/{breed2}/images
            Method: GET
      Environment:
        Variables:
          IMAGE_BUCKET_NAME: "IMAGE_BUCKET_NAME env var is empty"
          FILE_BUCKET_NAME: "FILE_BUCKET_NAME env var is empty"
          BUCKET_REGION: "BUCKET_REGION env var is empty"
          CDN_DOMAIN_PREFIX: ""
  listMasterBreedImageRandom:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: bin/
      Handler: listMasterBreedImageRandom
      Runtime: go1.x
      Role: arn:aws:iam::633322954385:role/dog-ceo-api-golang-dev-sam
      Events:
        CatchAll:
          Type: Api
          Properties:
            Path: /breed/{breed1}/images/random
            Method: GET
      Environment:
        Variables:
          IMAGE_BUCKET_NAME: "IMAGE_BUCKET_NAME env var is empty"
          FILE_BUCKET_NAME: "FILE_BUCKET_NAME env var is empty"
          BUCKET_REGION: "BUCKET_REGION env var is empty"
          CDN_DOMAIN_PREFIX: ""
  listSubBreedImageRandom:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: bin/
      Handler: listSubBreedImageRandom
      Runtime: go1.x
      Role: arn:aws:iam::633322954385:role/dog-ceo-api-golang-dev-sam
      Events:
        CatchAll:
          Type: Api
          Properties:
            Path: /breed/{breed1}/{breed2}/images/random
            Method: GET
      Environment:
        Variables:
          IMAGE_BUCKET_NAME: "IMAGE_BUCKET_NAME env var is empty"
          FILE_BUCKET_NAME: "FILE_BUCKET_NAME env var is empty"
          BUCKET_REGION: "BUCKET_REGION env var is empty"
          CDN_DOMAIN_PREFIX: ""
  listAnyBreedImageRandom:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: bin/
      Handler: listAnyBreedImageRandom
      Runtime: go1.x
      Role: arn:aws:iam::633322954385:role/dog-ceo-api-golang-dev-sam
      Events:
        CatchAll:
          Type: Api
          Properties:
            Path: /breeds/image/random
            Method: GET
      Environment:
        Variables:
          IMAGE_BUCKET_NAME: "IMAGE_BUCKET_NAME env var is empty"
          FILE_BUCKET_NAME: "FILE_BUCKET_NAME env var is empty"
          BUCKET_REGION: "BUCKET_REGION env var is empty"
          CDN_DOMAIN_PREFIX: ""
  listAnyBreedMultiImageRandom:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: bin/
      Handler: listAnyBreedMultiImageRandom
      Runtime: go1.x
      Role: arn:aws:iam::633322954385:role/dog-ceo-api-golang-dev-sam
      Events:
        CatchAll:
          Type: Api
          Properties:
            Path: /breeds/image/random/{count}
            Method: GET
      Environment:
        Variables:
          IMAGE_BUCKET_NAME: "IMAGE_BUCKET_NAME env var is empty"
          FILE_BUCKET_NAME: "FILE_BUCKET_NAME env var is empty"
          BUCKET_REGION: "BUCKET_REGION env var is empty"
          CDN_DOMAIN_PREFIX: ""
  listMasterBreedInfo:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: bin/
      Handler: listMasterBreedInfo
      Runtime: go1.x
      Role: arn:aws:iam::633322954385:role/dog-ceo-api-golang-dev-sam
      Events:
        CatchAll:
          Type: Api
          Properties:
            Path: /breed/{breed1}
            Method: GET
      Environment:
        Variables:
          IMAGE_BUCKET_NAME: "IMAGE_BUCKET_NAME env var is empty"
          FILE_BUCKET_NAME: "FILE_BUCKET_NAME env var is empty"
          BUCKET_REGION: "BUCKET_REGION env var is empty"
          CDN_DOMAIN_PREFIX: ""
  listSubBreedInfo:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: bin/
      Handler: listSubBreedInfo
      Runtime: go1.x
      Role: arn:aws:iam::633322954385:role/dog-ceo-api-golang-dev-sam
      Events:
        CatchAll:
          Type: Api
          Properties:
            Path: /breed/{breed1}/{breed2}
            Method: GET
      Environment:
        Variables:
          IMAGE_BUCKET_NAME: "IMAGE_BUCKET_NAME env var is empty"
          FILE_BUCKET_NAME: "FILE_BUCKET_NAME env var is empty"
          BUCKET_REGION: "BUCKET_REGION env var is empty"
          CDN_DOMAIN_PREFIX: ""
