AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  dog-ceo-api-golang
  
  The golang api for https://dog.ceo

Globals:
  Function:
    Timeout: 5

Resources:
  listAllBreeds:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: bin/
      Handler: allBreeds
      Runtime: provided.al2
      Role: arn:aws:iam::633322954385:role/dog-ceo-api-golang-dev-sam
      Events:
        CatchAll:
          Type: Api
          Properties:
            Path: /breeds/list/all
            Method: GET
      Environment:
        Variables:
          IMAGE_BUCKET_NAME: "dog-ceo-stanford-files"
          FILE_BUCKET_NAME: "dog-ceo-api-static-content-dev"
          BUCKET_REGION: "eu-west-1"
          CDN_DOMAIN_PREFIX: "https://images.dog.ceo/breeds/"
  listMasterBreeds:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: bin/
      Handler: masterBreeds
      Runtime: provided.al2
      Role: arn:aws:iam::633322954385:role/dog-ceo-api-golang-dev-sam
      Events:
        CatchAll:
          Type: Api
          Properties:
            Path: /breeds/list
            Method: GET
      Environment:
        Variables:
          IMAGE_BUCKET_NAME: "dog-ceo-stanford-files"
          FILE_BUCKET_NAME: "dog-ceo-api-static-content-dev"
          BUCKET_REGION: "eu-west-1"
          CDN_DOMAIN_PREFIX: "https://images.dog.ceo/breeds/"
  listSubBreeds:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: bin/
      Handler: subBreeds
      Runtime: provided.al2
      Role: arn:aws:iam::633322954385:role/dog-ceo-api-golang-dev-sam
      Events:
        CatchAll:
          Type: Api
          Properties:
            Path: /breed/{breed1}/list
            Method: GET
      Environment:
        Variables:
          IMAGE_BUCKET_NAME: "dog-ceo-stanford-files"
          FILE_BUCKET_NAME: "dog-ceo-api-static-content-dev"
          BUCKET_REGION: "eu-west-1"
          CDN_DOMAIN_PREFIX: "https://images.dog.ceo/breeds/"
  listMasterBreedImages:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: bin/
      Handler: breedImages
      Runtime: provided.al2
      Role: arn:aws:iam::633322954385:role/dog-ceo-api-golang-dev-sam
      Events:
        CatchAll:
          Type: Api
          Properties:
            Path: /breed/{breed1}/images
            Method: GET
      Environment:
        Variables:
          IMAGE_BUCKET_NAME: "dog-ceo-stanford-files"
          FILE_BUCKET_NAME: "dog-ceo-api-static-content-dev"
          BUCKET_REGION: "eu-west-1"
          CDN_DOMAIN_PREFIX: "https://images.dog.ceo/breeds/"
  listSubBreedImages:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: bin/
      Handler: breedImages
      Runtime: provided.al2
      Role: arn:aws:iam::633322954385:role/dog-ceo-api-golang-dev-sam
      Events:
        CatchAll:
          Type: Api
          Properties:
            Path: /breed/{breed1}/{breed2}/images
            Method: GET
      Environment:
        Variables:
          IMAGE_BUCKET_NAME: "dog-ceo-stanford-files"
          FILE_BUCKET_NAME: "dog-ceo-api-static-content-dev"
          BUCKET_REGION: "eu-west-1"
          CDN_DOMAIN_PREFIX: "https://images.dog.ceo/breeds/"
  listMasterBreedImageRandom:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: bin/
      Handler: breedImageRandom
      Runtime: provided.al2
      Role: arn:aws:iam::633322954385:role/dog-ceo-api-golang-dev-sam
      Events:
        CatchAll:
          Type: Api
          Properties:
            Path: /breed/{breed1}/images/random
            Method: GET
      Environment:
        Variables:
          IMAGE_BUCKET_NAME: "dog-ceo-stanford-files"
          FILE_BUCKET_NAME: "dog-ceo-api-static-content-dev"
          BUCKET_REGION: "eu-west-1"
          CDN_DOMAIN_PREFIX: "https://images.dog.ceo/breeds/"
  listSubBreedImageRandom:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: bin/
      Handler: breedImageRandom
      Runtime: provided.al2
      Role: arn:aws:iam::633322954385:role/dog-ceo-api-golang-dev-sam
      Events:
        CatchAll:
          Type: Api
          Properties:
            Path: /breed/{breed1}/{breed2}/images/random
            Method: GET
      Environment:
        Variables:
          IMAGE_BUCKET_NAME: "dog-ceo-stanford-files"
          FILE_BUCKET_NAME: "dog-ceo-api-static-content-dev"
          BUCKET_REGION: "eu-west-1"
          CDN_DOMAIN_PREFIX: "https://images.dog.ceo/breeds/"
  listAnyBreedImageRandom:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: bin/
      Handler: anyBreedMultiImageRandom
      Runtime: provided.al2
      Role: arn:aws:iam::633322954385:role/dog-ceo-api-golang-dev-sam
      Events:
        CatchAll:
          Type: Api
          Properties:
            Path: /breeds/image/random
            Method: GET
      Environment:
        Variables:
          IMAGE_BUCKET_NAME: "dog-ceo-stanford-files"
          FILE_BUCKET_NAME: "dog-ceo-api-static-content-dev"
          BUCKET_REGION: "eu-west-1"
          CDN_DOMAIN_PREFIX: "https://images.dog.ceo/breeds/"
  listAnyBreedMultiImageRandom:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: bin/
      Handler: anyBreedMultiImageRandom
      Runtime: provided.al2
      Role: arn:aws:iam::633322954385:role/dog-ceo-api-golang-dev-sam
      Events:
        CatchAll:
          Type: Api
          Properties:
            Path: /breeds/image/random/{count}
            Method: GET
      Environment:
        Variables:
          IMAGE_BUCKET_NAME: "dog-ceo-stanford-files"
          FILE_BUCKET_NAME: "dog-ceo-api-static-content-dev"
          BUCKET_REGION: "eu-west-1"
          CDN_DOMAIN_PREFIX: "https://images.dog.ceo/breeds/"
  listMasterBreedInfo:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: bin/
      Handler: breedInfo
      Runtime: provided.al2
      Role: arn:aws:iam::633322954385:role/dog-ceo-api-golang-dev-sam
      Events:
        CatchAll:
          Type: Api
          Properties:
            Path: /breed/{breed1}
            Method: GET
      Environment:
        Variables:
          IMAGE_BUCKET_NAME: "dog-ceo-stanford-files"
          FILE_BUCKET_NAME: "dog-ceo-api-static-content-dev"
          BUCKET_REGION: "eu-west-1"
          CDN_DOMAIN_PREFIX: "https://images.dog.ceo/breeds/"
  listSubBreedInfo:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: bin/
      Handler: breedInfo
      Runtime: provided.al2
      Role: arn:aws:iam::633322954385:role/dog-ceo-api-golang-dev-sam
      Events:
        CatchAll:
          Type: Api
          Properties:
            Path: /breed/{breed1}/{breed2}
            Method: GET
      Environment:
        Variables:
          IMAGE_BUCKET_NAME: "dog-ceo-stanford-files"
          FILE_BUCKET_NAME: "dog-ceo-api-static-content-dev"
          BUCKET_REGION: "eu-west-1"
          CDN_DOMAIN_PREFIX: "https://images.dog.ceo/breeds/"
