AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  dog-ceo-api-golang
  
  Sample SAM Template for dog-ceo-api-golang

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 5

Resources:
  listAllBreeds:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: bin/
      Handler: listAllBreeds
      Runtime: go1.x
      Tracing: Active # https://docs.aws.amazon.com/lambda/latest/dg/lambda-x-ray.html
      Events:
        CatchAll:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /breeds/list/all
            Method: GET
      Environment: # More info about Env Vars: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#environment-object
        Variables:
          IMAGE_BUCKET_NAME: "IMAGE_BUCKET_NAME env var is empty"
          FILE_BUCKET_NAME: "FILE_BUCKET_NAME env var is empty"
          BUCKET_REGION: "BUCKET_REGION env var is empty"
          CDN_DOMAIN_PREFIX: ""
  listBreeds:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: bin/
      Handler: listBreeds
      Runtime: go1.x
      Tracing: Active # https://docs.aws.amazon.com/lambda/latest/dg/lambda-x-ray.html
      Events:
        CatchAll:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /breeds/list
            Method: GET
      Environment: # More info about Env Vars: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#environment-object
        Variables:
          IMAGE_BUCKET_NAME: "IMAGE_BUCKET_NAME env var is empty"
          FILE_BUCKET_NAME: "FILE_BUCKET_NAME env var is empty"
          BUCKET_REGION: "BUCKET_REGION env var is empty"
          CDN_DOMAIN_PREFIX: ""
  listSubBreeds:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: bin/
      Handler: listSubBreeds
      Runtime: go1.x
      Tracing: Active # https://docs.aws.amazon.com/lambda/latest/dg/lambda-x-ray.html
      Events:
        CatchAll:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /breed/{breed}/list
            Method: GET
      Environment: # More info about Env Vars: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#environment-object
        Variables:
          IMAGE_BUCKET_NAME: "IMAGE_BUCKET_NAME env var is empty"
          FILE_BUCKET_NAME: "FILE_BUCKET_NAME env var is empty"
          BUCKET_REGION: "BUCKET_REGION env var is empty"
          CDN_DOMAIN_PREFIX: ""
  listMasterBreedImages:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: bin/
      Handler: listMasterBreedImages
      Runtime: go1.x
      Tracing: Active # https://docs.aws.amazon.com/lambda/latest/dg/lambda-x-ray.html
      Events:
        CatchAll:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /breed/{breed}/images
            Method: GET
      Environment: # More info about Env Vars: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#environment-object
        Variables:
          IMAGE_BUCKET_NAME: "IMAGE_BUCKET_NAME env var is empty"
          FILE_BUCKET_NAME: "FILE_BUCKET_NAME env var is empty"
          BUCKET_REGION: "BUCKET_REGION env var is empty"
          CDN_DOMAIN_PREFIX: ""
  listSubBreedImages:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: bin/
      Handler: listSubBreedImages
      Runtime: go1.x
      Tracing: Active # https://docs.aws.amazon.com/lambda/latest/dg/lambda-x-ray.html
      Events:
        CatchAll:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /breed/{breed1}/{breed2}/images
            Method: GET
      Environment: # More info about Env Vars: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#environment-object
        Variables:
          IMAGE_BUCKET_NAME: "IMAGE_BUCKET_NAME env var is empty"
          FILE_BUCKET_NAME: "FILE_BUCKET_NAME env var is empty"
          BUCKET_REGION: "BUCKET_REGION env var is empty"
          CDN_DOMAIN_PREFIX: ""
  listMasterBreedImageRandom:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: bin/
      Handler: listMasterBreedImageRandom
      Runtime: go1.x
      Tracing: Active # https://docs.aws.amazon.com/lambda/latest/dg/lambda-x-ray.html
      Events:
        CatchAll:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /breed/{breed}/images/random
            Method: GET
      Environment: # More info about Env Vars: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#environment-object
        Variables:
          IMAGE_BUCKET_NAME: "IMAGE_BUCKET_NAME env var is empty"
          FILE_BUCKET_NAME: "FILE_BUCKET_NAME env var is empty"
          BUCKET_REGION: "BUCKET_REGION env var is empty"
          CDN_DOMAIN_PREFIX: ""
  listSubBreedImageRandom:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: bin/
      Handler: listSubBreedImageRandom
      Runtime: go1.x
      Tracing: Active # https://docs.aws.amazon.com/lambda/latest/dg/lambda-x-ray.html
      Events:
        CatchAll:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /breed/{breed1}/{breed2}/images/random
            Method: GET
      Environment: # More info about Env Vars: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#environment-object
        Variables:
          IMAGE_BUCKET_NAME: "IMAGE_BUCKET_NAME env var is empty"
          FILE_BUCKET_NAME: "FILE_BUCKET_NAME env var is empty"
          BUCKET_REGION: "BUCKET_REGION env var is empty"
          CDN_DOMAIN_PREFIX: ""
  listAnyBreedImageRandom:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: bin/
      Handler: listAnyBreedImageRandom
      Runtime: go1.x
      Tracing: Active # https://docs.aws.amazon.com/lambda/latest/dg/lambda-x-ray.html
      Events:
        CatchAll:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /breeds/image/random
            Method: GET
      Environment: # More info about Env Vars: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#environment-object
        Variables:
          IMAGE_BUCKET_NAME: "IMAGE_BUCKET_NAME env var is empty"
          FILE_BUCKET_NAME: "FILE_BUCKET_NAME env var is empty"
          BUCKET_REGION: "BUCKET_REGION env var is empty"
          CDN_DOMAIN_PREFIX: ""
  listAnyBreedMultiImageRandom:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: bin/
      Handler: listAnyBreedMultiImageRandom
      Runtime: go1.x
      Tracing: Active # https://docs.aws.amazon.com/lambda/latest/dg/lambda-x-ray.html
      Events:
        CatchAll:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /breeds/image/random/{count}
            Method: GET
      Environment: # More info about Env Vars: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#environment-object
        Variables:
          IMAGE_BUCKET_NAME: "IMAGE_BUCKET_NAME env var is empty"
          FILE_BUCKET_NAME: "FILE_BUCKET_NAME env var is empty"
          BUCKET_REGION: "BUCKET_REGION env var is empty"
          CDN_DOMAIN_PREFIX: ""
  listMasterBreedInfo:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: bin/
      Handler: listMasterBreedInfo
      Runtime: go1.x
      Tracing: Active # https://docs.aws.amazon.com/lambda/latest/dg/lambda-x-ray.html
      Events:
        CatchAll:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /breed/{breed}
            Method: GET
      Environment: # More info about Env Vars: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#environment-object
        Variables:
          IMAGE_BUCKET_NAME: "IMAGE_BUCKET_NAME env var is empty"
          FILE_BUCKET_NAME: "FILE_BUCKET_NAME env var is empty"
          BUCKET_REGION: "BUCKET_REGION env var is empty"
          CDN_DOMAIN_PREFIX: ""
  listSubBreedInfo:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: bin/
      Handler: listSubBreedInfo
      Runtime: go1.x
      Tracing: Active # https://docs.aws.amazon.com/lambda/latest/dg/lambda-x-ray.html
      Events:
        CatchAll:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /breed/{breed1}/{breed2}
            Method: GET
      Environment: # More info about Env Vars: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#environment-object
        Variables:
          IMAGE_BUCKET_NAME: "IMAGE_BUCKET_NAME env var is empty"
          FILE_BUCKET_NAME: "FILE_BUCKET_NAME env var is empty"
          BUCKET_REGION: "BUCKET_REGION env var is empty"
          CDN_DOMAIN_PREFIX: ""

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  HelloWorldAPI:
    Description: "API Gateway endpoint URL for Prod environment for First Function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello/"
  listAllBreeds:
    Description: "First Lambda Function ARN"
    Value: !GetAtt listAllBreeds.Arn
  HelloWorldFunctionIamRole:
    Description: "Implicit IAM Role created for Hello World function"
    Value: !GetAtt HelloWorldFunctionRole.Arn
